/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 bucket.glb 
*/

import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/bucket.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Bucket_low_Bucket_low_0.geometry}>
          <meshStandardMaterial color={`green`}/>
      </mesh>
      <mesh geometry={nodes.Handle_low_Handle_low_0.geometry}>
          <meshStandardMaterial color={`blue`}/>
      </mesh>
      <mesh geometry={nodes.Label_low_Label_low_0.geometry}>
          <meshStandardMaterial color={`green`}/>
      </mesh>
      <mesh geometry={nodes.Pins_low_Pins_low_0.geometry}>
          <meshStandardMaterial color={`blue`}/>
      </mesh>
    </group>
  )
}

useGLTF.preload('/bucket.glb')
