/*
Cleo's component
Using three.js for the 3d model with React Three Fiber for React integration
+ useFrame for animations from R3F
Using gltfjsx from React Three Drei to import .gltf 3d model edited in Blender
Model credit: https://sketchfab.com/3d-models/paint-bucket-a1babccfb597490e84dc407a1e47a7fb
I did _not_ make the model myself; I simply made small edits in Blender
 */

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 bucket.glb
*/

/*
This is mostly an auto-generated file from gltfjsx (npx gltfjsx bucket.glb) with some edits marked below
 */

import { useGLTF } from '@react-three/drei'; // automatic import for .gltf calls
import {useRef} from 'react';
import {useFrame} from '@react-three/fiber';

export function Model(props) {

    /*START ANIMATION CODE*/
    const ref = useRef();
    useFrame((state, delta) => { // continuously request new animation frames
        ref.current.rotation.y += delta // on each frame, rotate the model by _delta_ (amt. of time a frame is active)
    })
    /*END ANIMATION CODE*/

  const { nodes, materials } = useGLTF('/bucket.glb')
    /*START MODEL CODE*/
  return (
    <group {...props} dispose={null} ref={ref}>             {/*_ref_ attribute animates the model as a whole*/}
        {/*color attribute passed as prop to allow for Paige's component to change it*/}
        <mesh geometry={nodes.Bucket_low_Bucket_low_0_1.geometry}>  {/*Removed texture from model and replaced with default*/}
            <meshStandardMaterial color={props.color}/>
        </mesh>
        <mesh geometry={nodes.Bucket_low_Bucket_low_0_2.geometry}>  {/*""*/}
            <meshStandardMaterial color={props.color}/>
        </mesh>
        <mesh geometry={nodes.Bucket_low_Bucket_low_0_3.geometry}>  {/*""*/}
            <meshStandardMaterial color={props.color}/>
        </mesh>
    </group>
  )
}
/*END MODEL CODE*/

useGLTF.preload('/bucket.glb')
